import { defaultSchema } from 'rehype-sanitize'

/**
 * Sanitisation schema for {@link rehype-sanitize}.
 *
 * ## Threat model
 * The primary XSS defence is that react-markdown does **not** render raw HTML by
 * default — so `<script>`, `<iframe>`, `onerror=` handlers etc. in the source are
 * inert unless `features.allowHtml` is explicitly enabled. When it is, the
 * pipeline is `rehype-raw` → `rehype-sanitize` so any parsed HTML is scrubbed
 * against this schema before it can reach the DOM.
 *
 * ## Why this schema is small
 * KaTeX and Shiki both run **after** sanitisation in the pipeline (or entirely
 * outside it, inside CodeBlock), operating on already-sanitised placeholder
 * nodes. Their output is generated by trusted code from escaped input, so we do
 * not need to whitelist the hundreds of MathML/`<span>` styling tags KaTeX emits.
 * That keeps the attack surface minimal.
 *
 * We extend the library default only for genuine GFM/markdown needs:
 *  - `input[type=checkbox]` for task lists,
 *  - `id` on headings for anchor links,
 *  - `className` on the elements our renderer/plugins legitimately class,
 *  - `target`/`rel` on links (belt-and-braces; LinkRenderer also enforces these).
 */
export const sanitizeSchema = {
  ...defaultSchema,
  tagNames: [...(defaultSchema.tagNames ?? []), 'input'],
  attributes: {
    ...defaultSchema.attributes,
    '*': [
      ...(defaultSchema.attributes?.['*'] ?? []),
      'className',
      'id',
    ],
    // GFM task-list checkboxes are rendered as disabled inputs.
    input: ['type', 'checked', 'disabled'],
    a: [
      ...(defaultSchema.attributes?.a ?? []),
      'target',
      'rel',
    ],
    code: [
      ...(defaultSchema.attributes?.code ?? []),
      ['className', /^language-./, 'hljs', 'math', 'math-inline', 'math-display'],
    ],
    span: [
      ...(defaultSchema.attributes?.span ?? []),
      ['className', /.*/],
    ],
  },
  // Only allow safe URL protocols on links/images. Blocks `javascript:` URIs.
  protocols: {
    ...defaultSchema.protocols,
    href: ['http', 'https', 'mailto', 'tel', '#'],
    src: ['http', 'https', 'data'],
  },
} as const

export type SanitizeSchema = typeof sanitizeSchema
